# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

title: "Edge Applications"
path: /applications/
order: 5
section:
  - title: Application Development & Porting Guide
    path: /doc/applications/openness_appguide
    meta_title: Application Development and Porting Guide
    meta_description: OpenNESS is an open source software toolkit to enable easy orchestration of edge services across diverse network platform and access technologies in multi-cloud environments. 

  - title: OVC Smart City Application
    path: /doc/applications/openness_ovc
    meta_title: Open Visual Cloud Smart City Application on OpenNESS
    meta_description: The Open Visual Cloud is an open source project that offers a set of pre-defined reference pipelines for various target visual cloud use cases.

  - title: Intel OpenVINO Sample Application
    path: /doc/applications/openness_openvino
    meta_title: OpenVINO Sample Application in OpenNESS
    meta_description: OpenVINO toolkit, short for Open Visual Inference and Neural network Optimization toolkit, provides improved neural network performance on Intel processors.

  - title: OpenNESS Video Analytics Services
    path: /doc/applications/openness_va_services
    meta_title: OpenNESS Video Analytics Services
    meta_description: The Video Analytics Services provided by OpenNESS to enable third party edge application to deploy and use hardware optimized video analytics pipelines.

  - title: OpenNESS Service Mesh
    path: /doc/applications/openness_service_mesh
    meta_title: OpenNESS Service Mesh
    meta_description: Service mesh acts as a middleware between the edge applications/services and the OpenNESS platform providing abstractions for traffic management, observability and security for the edge micro-services.
